added pm2 path

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,7 +29,7 @@ jobs:
           script: |
             cd /www/wwwroot/mobin
             echo "Creating 'frontend' directory..."
-            mkdir frontend
+            mkdir -p frontend
             cd frontend
 
             git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mobinrayhan/personal-portfolio.git .
@@ -39,12 +39,15 @@ jobs:
             nvm install 22
             nvm use 22
 
+            export PATH=$PATH:/www/server/nvm/versions/node/v22.13.0/bin # Add pm2 to PATH
+            pm2 -v || echo "pm2 is not found in PATH"
+
             npm ci
             npm run build
+
             pm2 restart mobin_front
             rm -rf .github/
             rm -rf .git/
-
   # Deploy:
   # Deploy:
   #   runs-on: ubuntu-latest
